"""Contract fixture parity + staleness tests (Release 2.2, Commit 10).

Plain-Python, no pytest. Proves that the committed cross-language contract
fixtures are:

  * CURRENT      -- byte-identical to a fresh regeneration (no drift);
  * FAITHFUL     -- each request/response re-validates against the REAL Python
                    contracts (round-trip through the Pydantic models);
  * GOVERNED     -- only completed, execution-eligible missions carry an
                    executable MissionExecutionPayload; blocked / rejected /
                    revision / error fixtures carry none;
  * SAFE         -- no PersonaResponse, no credentials, no database paths, no
                    SQL, no stack traces cross the boundary;
  * WIRE-SHAPED  -- camelCase keys only (snake_case never emitted);
  * BOUND        -- the approved action-payload hash links approval <-> receipt.

Run directly:  python services/api/harness/tests/test_contract_fixtures.py
"""

from __future__ import annotations

import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_API_DIR = os.path.abspath(os.path.join(_HERE, "..", ".."))
if _API_DIR not in sys.path:
    sys.path.insert(0, _API_DIR)

from harness.generate_contract_fixtures import (  # noqa: E402
    FIXTURES_DIR,
    build_all,
    check_all,
)
from harness.service import (  # noqa: E402
    HarnessServiceRequest,
    HarnessServiceResponse,
)

_RESULTS: list[tuple[str, bool, str]] = []


def _check(name: str, condition: bool, detail: str = "") -> None:
    _RESULTS.append((name, bool(condition), detail))


def _load(filename: str) -> dict:
    with open(os.path.join(FIXTURES_DIR, filename), "r", encoding="utf-8") as handle:
        return json.load(handle)


def _manifest() -> dict:
    return _load("manifest.json")


# A camelCase contract field never contains an underscore. Free-form MAP fields
# carry domain data whose keys are NOT part of the contract naming convention
# (signal payloads, injected-timestamp stage names, simulated-action detail, and
# opaque before/after state), so we do not descend into their values.
_SNAKE_KEY = re.compile(r"_")
_FREEFORM_FIELDS = frozenset({
    "signals", "signalContext", "injectedTimestamps", "details",
    "beforeState", "afterState",
})


def _all_keys(node: object):
    """Yield every contract field key, pruning free-form map subtrees."""
    if isinstance(node, dict):
        for key, value in node.items():
            yield key
            if key in _FREEFORM_FIELDS:
                continue  # opaque domain map: its keys are not contract fields
            yield from _all_keys(value)
    elif isinstance(node, list):
        for item in node:
            yield from _all_keys(item)


_FORBIDDEN_TOKENS = (
    "personaResponse", "persona_response", "PersonaResponse",
    "voiceSummary", "voice_summary",
    "Traceback", "sqlite", ":memory:", "SELECT ", "INSERT ",
    "IdempotencyConflictError", "AuditIdempotencyConflictError",
    "password", "apiKey", "api_key", "secret", "Bearer ",
    "C:\\", "/Users/", ".sqlite",
)


# -- staleness / determinism ------------------------------------------------


def test_fixtures_are_current() -> None:
    ok, problems = check_all(FIXTURES_DIR)
    _check("committed fixtures are current (no drift)", ok, "; ".join(problems))


def test_regeneration_is_byte_identical() -> None:
    first = build_all()
    second = build_all()
    _check("regeneration is deterministic (byte-identical)", first == second)
    # And the committed file bytes equal the generated bytes.
    for filename, text in first.items():
        path = os.path.join(FIXTURES_DIR, filename)
        with open(path, "r", encoding="utf-8") as handle:
            _check(f"{filename} matches generator bytes", handle.read() == text)


def test_expected_fixture_set_present() -> None:
    expected = {
        "01_completed_renewal_risk.json",
        "02_completed_support_escalation.json",
        "03_blocked_unsupported_signal.json",
        "04_blocked_ambiguous_account.json",
        "05_rejected_approval.json",
        "06_revision_required.json",
        "07_error_idempotency_conflict.json",
        "08_error_internal_safe_failure.json",
        "manifest.json",
    }
    on_disk = {f for f in os.listdir(FIXTURES_DIR) if f.endswith(".json")}
    _check("exactly the expected fixture set exists", on_disk == expected,
           f"disk={sorted(on_disk)}")


# -- round-trip fidelity ----------------------------------------------------


def _fixture_files() -> list[str]:
    return [entry["file"] for entry in _manifest()["fixtures"]]


def test_requests_and_responses_round_trip() -> None:
    for filename in _fixture_files():
        env = _load(filename)
        # Requests accept camelCase (populate_by_name / alias) -> re-validate.
        req = HarnessServiceRequest.model_validate(env["request"])
        req_again = req.model_dump(by_alias=True, mode="json")
        _check(f"{filename} request re-serializes to camelCase",
               req_again["requestId"] == env["request"]["requestId"])
        resp = HarnessServiceResponse.model_validate(env["response"])
        _check(f"{filename} response round-trips through the model",
               resp.status == env["response"]["status"])
        _check(f"{filename} response result hash preserved",
               resp.result_hash == env["response"]["resultHash"])


def test_manifest_matches_responses() -> None:
    for entry in _manifest()["fixtures"]:
        env = _load(entry["file"])
        resp = env["response"]
        _check(f"{entry['file']} manifest status matches", entry["status"] == resp["status"])
        _check(f"{entry['file']} manifest hash matches", entry["resultHash"] == resp["resultHash"])
        _check(f"{entry['file']} manifest payload flag matches",
               entry["hasExecutionPayload"] == (resp.get("missionExecutionPayload") is not None))


# -- governance: payload only for governance-valid missions -----------------


def test_completed_fixtures_carry_executable_payload() -> None:
    for filename in ("01_completed_renewal_risk.json", "02_completed_support_escalation.json"):
        env = _load(filename)
        resp = env["response"]
        _check(f"{filename} status completed", resp["status"] == "completed", resp["status"])
        _check(f"{filename} execution eligible", resp["executionEligible"] is True)
        payload = resp.get("missionExecutionPayload")
        _check(f"{filename} carries a payload", payload is not None)
        _check(f"{filename} payload simulated=true", bool(payload and payload["simulated"]) is True)
        _check(f"{filename} payload has selectedTemplateId",
               bool(payload and payload.get("selectedTemplateId")))
        _check(f"{filename} payload has permittedActions",
               bool(payload and payload.get("permittedActions")))
        _check(f"{filename} payload carries no PersonaResponse",
               payload is not None and "personaResponse" not in payload)


def test_non_completed_fixtures_have_no_payload() -> None:
    for filename in (
        "03_blocked_unsupported_signal.json",
        "04_blocked_ambiguous_account.json",
        "05_rejected_approval.json",
        "06_revision_required.json",
        "07_error_idempotency_conflict.json",
        "08_error_internal_safe_failure.json",
    ):
        env = _load(filename)
        resp = env["response"]
        _check(f"{filename} not completed", resp["status"] != "completed", resp["status"])
        _check(f"{filename} execution ineligible", resp["executionEligible"] is False)
        _check(f"{filename} produces no executable payload",
               resp.get("missionExecutionPayload") is None)


def test_blocked_ambiguous_fabricates_no_canonical_account() -> None:
    env = _load("04_blocked_ambiguous_account.json")
    result = env["response"]["missionEvaluationResult"]
    _check("ambiguous identity has null canonical account",
           result is not None and result.get("canonicalAccount") is None)
    _check("ambiguous identity did not select a template",
           result is not None and not result.get("selectedTemplateId"))


# -- typed error codes ------------------------------------------------------


def test_error_and_blocked_codes() -> None:
    expected = {
        "03_blocked_unsupported_signal.json": ("blocked", "no_matching_template"),
        "04_blocked_ambiguous_account.json": ("blocked", "ambiguous_identity"),
        "05_rejected_approval.json": ("rejected", "approval_rejected"),
        "06_revision_required.json": ("revision_required", "verification_failed"),
        "07_error_idempotency_conflict.json": ("failed", "idempotency_conflict"),
        "08_error_internal_safe_failure.json": ("failed", "internal_service_failure"),
    }
    for filename, (status, code) in expected.items():
        env = _load(filename)
        resp = env["response"]
        _check(f"{filename} status is {status}", resp["status"] == status, resp["status"])
        errors = resp["serviceErrors"]
        _check(f"{filename} exposes exactly one service error", len(errors) == 1, str(errors))
        _check(f"{filename} error code is {code}",
               bool(errors) and errors[0]["code"] == code,
               errors[0]["code"] if errors else "<none>")


def test_idempotency_conflict_is_bff_safe() -> None:
    env = _load("07_error_idempotency_conflict.json")
    err = env["response"]["serviceErrors"][0]
    _check("idempotency conflict stage owns the failure", err["stage"] in ("audit", "execution"))
    _check("idempotency conflict not retryable", err["retryable"] is False)
    blob = json.dumps(env)
    leaked = [t for t in ("IdempotencyConflictError", "AuditIdempotencyConflictError",
                          "Traceback", "sqlite", ":memory:") if t in blob]
    _check("idempotency conflict leaks no internal type/trace", leaked == [], str(leaked))


# -- boundary safety: camelCase-only + no sensitive content -----------------


def test_no_snake_case_keys_on_the_wire() -> None:
    for filename in _fixture_files():
        env = _load(filename)
        # The request/response payloads are the wire contract; the envelope's own
        # metadata keys (name/description) are not part of it.
        for section in ("request", "response"):
            offenders = sorted({k for k in _all_keys(env[section]) if _SNAKE_KEY.search(k)})
            _check(f"{filename}::{section} emits only camelCase keys",
                   offenders == [], str(offenders))


def test_no_forbidden_tokens() -> None:
    for filename in _fixture_files():
        blob = json.dumps(_load(filename)[ "response"])
        hits = [t for t in _FORBIDDEN_TOKENS if t in blob]
        _check(f"{filename} response contains no forbidden tokens", hits == [], str(hits))


# -- approval <-> receipt binding -------------------------------------------


def test_approval_binds_to_simulated_receipt() -> None:
    for filename in ("01_completed_renewal_risk.json", "02_completed_support_escalation.json"):
        env = _load(filename)
        payload = env["response"]["missionExecutionPayload"]
        receipt = env["response"]["missionEvaluationResult"]["simulatedActionReceipt"]
        approval_hash = payload["approvalRequest"]["actionPayloadHash"]
        _check(f"{filename} approval payload hash present", bool(approval_hash))
        _check(f"{filename} approval hash binds to receipt approved hash",
               approval_hash == receipt["approvedPayloadHash"],
               f"{approval_hash} != {receipt['approvedPayloadHash']}")
        _check(f"{filename} receipt is simulated", receipt["simulated"] is True)


_TESTS = [
    test_fixtures_are_current,
    test_regeneration_is_byte_identical,
    test_expected_fixture_set_present,
    test_requests_and_responses_round_trip,
    test_manifest_matches_responses,
    test_completed_fixtures_carry_executable_payload,
    test_non_completed_fixtures_have_no_payload,
    test_blocked_ambiguous_fabricates_no_canonical_account,
    test_error_and_blocked_codes,
    test_idempotency_conflict_is_bff_safe,
    test_no_snake_case_keys_on_the_wire,
    test_no_forbidden_tokens,
    test_approval_binds_to_simulated_receipt,
]


def run() -> tuple[int, int]:
    for test in _TESTS:
        test()
    passed = sum(1 for _, ok, _ in _RESULTS if ok)
    failed = sum(1 for _, ok, _ in _RESULTS if not ok)
    for name, ok, detail in _RESULTS:
        if not ok:
            print(f"  FAIL  {name}" + (f" -- {detail}" if detail else ""))
    print(f"Contract fixtures: {passed} passed, {failed} failed, {len(_RESULTS)} checks total")
    return passed, failed


if __name__ == "__main__":
    _passed, _failed = run()
    sys.exit(1 if _failed else 0)
