// Release 2.2 — Mission BFF · Memory + Conversation adapter (F1.5)
// ===============================================================
// A NARROW, one-way adapter that maps a governance-valid, decision-closed
// `MissionExecutionPayload` (from the Python Adaptive Mission Harness) onto the
// EXISTING public TypeScript interfaces of the protected Memory Core (2.1A/2.1B)
// and the Conversation Runtime (2.1C). It is the seam where a completed mission
// gets its evidence retrieved and its language composed on the TypeScript side.
//
// Hard boundaries (LOCKED — this module MODIFIES nothing it depends on):
//   * It consumes memory only via `../memory` and the runtime only via
//     `../conversation` (their sanctioned barrels). It never reaches into
//     `lib/memory/**` or `lib/conversation/**` internals.
//   * It NEVER recomputes a Python decision: mission state, verification,
//     approval policy, recommendation, and the permitted action are forwarded
//     verbatim as governance context — never re-derived here.
//   * The PersonaResponse is generated by the TypeScript runtime (`composeResponse`),
//     never carried from Python.
//   * Time enters only as the injected `asOfMs`; the turn/session are injected.
//     No `Date.now()`, no randomness, no clock — the mapping is deterministic.
//   * Fallback behaviour is preserved HONESTLY: whatever the runtime returns for
//     empty / all-recent / low-confidence memory is surfaced unchanged; this
//     adapter fabricates no segments and no citations.

import { buildRetrievalQuery, composeResponse } from "../conversation";
import type {
  ConversationContext,
  ConversationIntent,
  ConversationSession,
  PersonaResponse,
  PersonaTone,
} from "../conversation";
import { MemoryStore } from "../memory";
import type { MemoryCategory, RetrievalQuery } from "../memory";
import type {
  ApprovalRequest,
  CanonicalAccountRef,
  EvidenceRef,
  MissionDefinitionBrief,
  MissionExecutionPayload,
  MissionState,
  RecommendationRef,
  VerificationResult,
} from "../harness/types";

// ---------------------------------------------------------------------------
// Errors — a governance-valid payload should always map cleanly; a structural
// violation fails CLOSED with a stable, BFF-safe code (never a payload dump).
// ---------------------------------------------------------------------------

export type MissionAdapterErrorCode =
  | "invalid_intent"
  | "subject_mismatch"
  | "missing_canonical_account";

export class MissionAdapterError extends Error {
  readonly code: MissionAdapterErrorCode;
  constructor(code: MissionAdapterErrorCode, message: string) {
    super(message);
    this.name = "MissionAdapterError";
    this.code = code;
  }
}

// ---------------------------------------------------------------------------
// Injected presentation/runtime dependencies
// ---------------------------------------------------------------------------

/** Presentation persona framing. Injected — the payload carries only a stable
 * `personaId`; tone/role are a presentation choice and never a Python decision. */
export interface MissionPersonaConfig {
  role: string;
  tone: PersonaTone;
  /** Optional display cap on woven memories (truncation only; never re-ranks). */
  maxSegments?: number;
}

export interface MissionMemoryDeps {
  /** The protected MemoryStore to READ (never mutated here). */
  store: MemoryStore;
  /** The runtime-owned session (turn + served history). Injected, caller-owned. */
  session: ConversationSession;
  /** Injected reference epoch-ms (the governed clock). Never `Date.now()`. */
  asOfMs: number;
  persona: MissionPersonaConfig;
}

// ---------------------------------------------------------------------------
// Governance context — forwarded verbatim, never recomputed
// ---------------------------------------------------------------------------

/** The decision-closed governance facts carried alongside the composed language.
 * Every field is forwarded from the Python payload UNCHANGED. */
export interface MissionGovernanceContext {
  missionId: string;
  missionState: MissionState;
  intent: ConversationIntent;
  selectedTemplateId: string;
  permittedActions: string[];
  evidenceRefs: EvidenceRef[];
  verification: VerificationResult;
  verificationRef: string;
  approvalRequest: ApprovalRequest | null;
  recommendation: RecommendationRef;
  missionDefinition: MissionDefinitionBrief | null;
  auditRef: string;
  simulated: true;
}

export interface MissionMemoryResult {
  /** The exact retrieval query executed against the protected store. */
  retrievalQuery: RetrievalQuery;
  /** The TypeScript-generated persona response (may be an honest fallback). */
  personaResponse: PersonaResponse;
  /** Forwarded governance facts (state / verification / approval / evidence). */
  governance: MissionGovernanceContext;
}

// ---------------------------------------------------------------------------
// Intent mapping (closed set — fail closed)
// ---------------------------------------------------------------------------

const VALID_INTENTS: ReadonlySet<string> = new Set<ConversationIntent>([
  "resume",
  "status",
  "risk_review",
  "next_step",
  "recap",
]);

/** Map the payload's governed intent string to a runtime `ConversationIntent`.
 * Fails closed on an unknown intent (never guesses a template family). */
export function mapPayloadIntent(intent: string): ConversationIntent {
  if (!VALID_INTENTS.has(intent)) {
    throw new MissionAdapterError(
      "invalid_intent",
      "The mission intent is not a supported conversation intent.",
    );
  }
  return intent as ConversationIntent;
}

// ---------------------------------------------------------------------------
// Payload -> ConversationContext (the retrieval + composition request)
// ---------------------------------------------------------------------------

function canonicalSubject(account: CanonicalAccountRef | undefined): string {
  if (!account || typeof account.ventureOsId !== "string" || account.ventureOsId.length === 0) {
    throw new MissionAdapterError(
      "missing_canonical_account",
      "The mission payload is missing a canonical account subject.",
    );
  }
  return account.ventureOsId;
}

/** Build the deterministic `ConversationContext` for a completed mission. The
 * canonical VentureOS id becomes the retrieval subject; the governed limit and
 * categories are preserved; `asOfMs` is the injected clock. */
export function mapPayloadToConversationContext(
  payload: MissionExecutionPayload,
  deps: MissionMemoryDeps,
): ConversationContext {
  const subjectId = canonicalSubject(payload.canonicalAccount);

  // The canonical account is the single governed identity; the Python-supplied
  // retrieval subject MUST agree with it. Disagreement is a contract violation.
  if (payload.retrievalQuery.subjectId !== subjectId) {
    throw new MissionAdapterError(
      "subject_mismatch",
      "The mission retrieval subject does not match the canonical account.",
    );
  }

  const ctx: ConversationContext = {
    persona: {
      id: payload.personaId,
      role: deps.persona.role,
      tone: deps.persona.tone,
    },
    intent: mapPayloadIntent(payload.intent),
    subjectId,
    limit: payload.retrievalQuery.limit,
    asOfMs: deps.asOfMs,
  };
  if (deps.persona.maxSegments !== undefined) {
    ctx.persona.maxSegments = deps.persona.maxSegments;
  }
  if (payload.retrievalQuery.categories && payload.retrievalQuery.categories.length > 0) {
    ctx.categories = payload.retrievalQuery.categories as MemoryCategory[];
  }
  return ctx;
}

/** Build the exact `RetrievalQuery` executed against the store (subjectId, the
 * governed limit, the injected `asOfMs`, and the session's anti-repetition
 * context). Preserves the canonical subject and the injected clock verbatim. */
export function mapPayloadToRetrievalQuery(
  payload: MissionExecutionPayload,
  deps: MissionMemoryDeps,
): RetrievalQuery {
  return buildRetrievalQuery(mapPayloadToConversationContext(payload, deps), deps.session);
}

// ---------------------------------------------------------------------------
// Governance context extraction (verbatim; no re-derivation)
// ---------------------------------------------------------------------------

/** Project the decision-closed governance facts from the payload UNCHANGED.
 * Approval (and, later, the action receipt) remain governance context here —
 * this adapter never approves, executes, or re-decides anything. */
export function extractGovernanceContext(
  payload: MissionExecutionPayload,
): MissionGovernanceContext {
  return {
    missionId: payload.missionId,
    missionState: payload.missionState,
    intent: mapPayloadIntent(payload.intent),
    selectedTemplateId: payload.selectedTemplateId,
    permittedActions: payload.permittedActions,
    evidenceRefs: payload.evidenceRefs,
    verification: payload.verification,
    verificationRef: payload.verificationRef,
    approvalRequest: payload.approvalRequest ?? null,
    recommendation: payload.recommendation,
    missionDefinition: payload.missionDefinition ?? null,
    auditRef: payload.auditRef,
    simulated: true,
  };
}

// ---------------------------------------------------------------------------
// The adapter entry point
// ---------------------------------------------------------------------------

/** Retrieve evidence and compose the persona response for a completed mission,
 * returning the composed language plus the forwarded governance context.
 *
 * Deterministic given `deps`: `composeResponse` reads the store only and never
 * re-ranks or re-scores, so the same payload + store + session + `asOfMs`
 * yields a byte-identical result. */
export function composeMissionMemory(
  payload: MissionExecutionPayload,
  deps: MissionMemoryDeps,
): MissionMemoryResult {
  const ctx = mapPayloadToConversationContext(payload, deps);
  const retrievalQuery = buildRetrievalQuery(ctx, deps.session);
  const personaResponse = composeResponse(deps.store, ctx, deps.session);
  const governance = extractGovernanceContext(payload);
  return { retrievalQuery, personaResponse, governance };
}
