"use client";

import * as React from "react";
import { Mail, Phone, Mic, Copy, Check } from "lucide-react";
import type { Recommendation } from "@/lib/types";
import { cx } from "@/lib/format";

type Tab = "email" | "call" | "voice";

export function DraftPanel({ rec, editing }: { rec: Recommendation; editing: boolean }) {
  const [tab, setTab] = React.useState<Tab>("email");
  const [copied, setCopied] = React.useState(false);

  // Local editable copies; reset whenever the selected recommendation changes.
  const [email, setEmail] = React.useState(rec.draft_email);
  const [call, setCall] = React.useState(rec.call_script);
  const [voice, setVoice] = React.useState(rec.voice_summary);
  React.useEffect(() => {
    setEmail(rec.draft_email);
    setCall(rec.call_script);
    setVoice(rec.voice_summary);
  }, [rec.recommendation_id, rec.draft_email, rec.call_script, rec.voice_summary]);

  const current = tab === "email" ? email : tab === "call" ? call : voice;
  const setCurrent = tab === "email" ? setEmail : tab === "call" ? setCall : setVoice;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(current);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };

  const tabs: Array<{ id: Tab; label: string; icon: React.ReactNode }> = [
    { id: "email", label: "Email", icon: <Mail size={13} /> },
    { id: "call", label: "Call script", icon: <Phone size={13} /> },
    { id: "voice", label: "Voice", icon: <Mic size={13} /> },
  ];

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between gap-2">
        <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-faint">
          <Mail size={12} className="text-cyan" />
          Seller-ready draft
        </span>
        <span className="rounded border border-accent/30 bg-accent/5 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wider text-accent">
          Ready for review
        </span>
      </div>
      <div className="flex items-center justify-between">
        <div className="flex gap-1">
          {tabs.map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={cx(
                "inline-flex items-center gap-1.5 rounded-md border px-2.5 py-1 text-xs font-medium transition-colors",
                tab === t.id
                  ? "border-accent/40 bg-accent/10 text-accent"
                  : "border-edge bg-surface2 text-muted hover:text-ink",
              )}
            >
              {t.icon}
              {t.label}
            </button>
          ))}
        </div>
        <button
          onClick={copy}
          className="inline-flex items-center gap-1.5 rounded-md border border-edge bg-surface2 px-2 py-1 text-xs text-muted hover:text-ink"
        >
          {copied ? <Check size={13} className="text-accent" /> : <Copy size={13} />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>

      <textarea
        readOnly={!editing}
        value={current}
        onChange={(e) => setCurrent(e.target.value)}
        className={cx(
          "h-52 w-full resize-none rounded-lg border bg-surface2/50 p-3 text-[12px] leading-relaxed text-muted outline-none",
          tab === "voice" ? "font-mono" : "font-sans",
          editing ? "border-accent/40 text-ink focus:border-accent" : "border-edge",
        )}
      />
      <p className="text-[10px] text-faint">
        {editing
          ? "Edit mode — tweak the draft before a human approves. Changes stay local to this review."
          : "Generated by the Communication Agent via the active model adapter. Click Edit to refine."}
      </p>
    </div>
  );
}
